default_stages: [commit]

repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.4.0
    hooks:
      - id: buildifier
        exclude: ".*\/assets.bzl$"
      - id: buildifier-lint
        exclude: ".*\/assets.bzl$"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: format
        name: Format
        language: system
        entry: bazel run //:format
        files: .*
