#!/usr/bin/env bash
#
# Create an `assets.bzl` file to put into `./toolchains/sha`.
#
# Its single argument is a file with all sha384 output files listed.
# The `$TAG` env variable is used to fulfill the url to the tools repository.

if [[ -z "${TAG:-}" ]]; then
    echo -e >&2 "\033[1mERROR\033[0m [$(basename "$0")]\nTAG is not defined. Aborting!\n"
    exit 1
fi

url="https://github.com/bzlparty/tools/releases/download/$TAG"

echo -e "\"This file was generated by $(basename "$0")\"\n"
echo "ASSETS = {"
for f in "$@"; do
  target_file=$(basename "$f")
  bin_file=${target_file%.*}
  platform=$(echo "$bin_file" | awk -F_ '{print $2 "_" $3}' | sed "s/\.exe//")
  echo "    \"$platform\": struct(binary = \"$bin_file\", url = \"$url/$bin_file\", integrity = \"sha384-$(< "$f")\"),"
done
echo "}"
